#
# Copyright (c) Siemens AG, 2025
#
# Authors:
#  Alexander Heinisch <alexander.heinisch@siemens.com>
#
# SPDX-License-Identifier: MIT
#

PXESERVER_TMPDIR ?= "${TOPDIR}/tmp-${PXESERVER_MC}-${MACHINE}"
TMPDIR = "${PXESERVER_TMPDIR}"

# installer
PXESERVER_MC = "pxe-boot-server"

PXE_TARGET_MACHINE ?= "vmware"
PXESERVER_LIVE_INSTALLER_MC ?= "pxe-boot-installer-target"
PXESERVER_LIVE_INSTALLER_MACHINE ?= "${PXE_TARGET_MACHINE}"
PXESERVER_LIVE_INSTALLER_IMAGE ?= "isar-image-installer"

PXESERVER_LIVE_INSTALLER_ADDITIONAL_KERNEL_CMDLINE:append:pxe-nfsroot = " root=/dev/nfs ro nfsroot=${PXESERVER_IP}:/var/installer/rootfs proto=tcp"

# Pull defined set of packages from Debian Trixie for Bookworm builds
DISTRO_APT_SOURCES:append:bookworm = " conf/trixie-for-pxeboot.list"
DISTRO_APT_PREFERENCES:append:bookworm = " conf/trixie-for-pxeboot.conf"
