#
# Copyright (c) Siemens AG, 2025
#
#
# SPDX-License-Identifier: MIT
#

MACHINE ?= "${PXE_TARGET_MACHINE}"

IMAGE_DATA_POSTFIX ??= "wic.zst"
TARGET_IMAGE_FSTYPE = "${IMAGE_DATA_POSTFIX}"

IMAGE_FSTYPES += "${TARGET_IMAGE_FSTYPE}"
