#
# Copyright (c) Siemens AG, 2025
#
# Authors:
#  Alexander Heinisch <alexander.heinisch@siemens.com>
#
# SPDX-License-Identifier: MIT
#

# installer
PXE_TARGET_MACHINE ??= "qemuamd64"

MACHINE = "${PXE_TARGET_MACHINE}"

PXESERVER_LIVE_INSTALLER_MC ?= "pxe-boot-installer-target"
PXESERVER_LIVE_INSTALLER_MACHINE ?= "${PXE_TARGET_MACHINE}"
PXESERVER_LIVE_INSTALLER_IMAGE ?= "isar-image-installer"

INSTALLER_MC ?= "${PXESERVER_LIVE_INSTALLER_MC}"
PXESERVER_LIVE_INSTALLER_IMAGE ?= "isar-image-installer"

INSTALLER_TARGET_MC ?= "pxe-boot-installer"
INSTALLER_TARGET_MACHINE ?= "${MACHINE}"
INSTALLER_TARGET_DISTRO ?= "${DISTRO}"

INSTALLER_TARGET_TMPDIR ?= "${TOPDIR}/tmp"
INSTALLER_TARGET_DEPLOY_DIR ?= "${INSTALLER_TARGET_TMPDIR}/deploy"
INSTALLER_TARGET_DEPLOY_DIR_IMAGE ?= "${INSTALLER_TARGET_DEPLOY_DIR}/images/${INSTALLER_TARGET_MACHINE}"

INSTALLER_TARGET_IMAGE ?= "isar-image-base"
IMAGE_DATA_FILE ?= "${INSTALLER_TARGET_IMAGE}-${INSTALLER_TARGET_DISTRO}-${INSTALLER_TARGET_MACHINE}"

ADDITIONAL_KERNEL_CMDLINE ?= ""

IMAGE_FSTYPES:append:pxe-nfsroot = " tar"

IMAGE_DATA_FILE ?= "${INSTALLER_TARGET_IMAGE}-${DISTRO}-${INSTALLER_TARGET_MACHINE}"
ADDITIONAL_KERNEL_CMDLINE:append:target-bootstrapper = " \
    installer.image.uri=/install/${IMAGE_DATA_FILE}.${IMAGE_DATA_POSTFIX} \
    installer.target.dev=${INSTALLER_TARGET_DEVICE} \
    installer.target.overwrite=OVERWRITE \
    "
