#!/bin/bash

# includes the default directory if no path is provided
if [[ $# -eq 0 || ( ! -f "${!#}" && ! -d "${!#}" ) ]]; then
    set -- "$@" "//tests"
fi

/usr/bin/bats --setup-suite-file /tests/setup_suite.bash --trace --verbose-run --recursive --formatter /usr/libexec/bats-core/bats-format-lava ${*}

# clear the testset for possible tests outside bats
echo "<LAVA_SIGNAL_TESTSET STOP>"
