#
# Copyright (c) Siemens AG, 2025
#
# SPDX-License-Identifier: MIT
#

spec:
  inputs:
    snapshot:
      description: "Set the snapshot date to use for debian packages (e.g.: \"20250507T083647Z\") - leave empty (\"\") to disables snapshots."
      default: "20250507T083647Z"

---

variables:
  https_proxy: ${CODE_PROXY}
  http_proxy: ${CODE_PROXY}
  no_proxy: ${CODE_NO_PROXY}
  BUILD_TAG: unreleased-${CI_COMMIT_SHORT_SHA}-$[[ inputs.snapshot ]]

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        BUILD_TAG: ${CI_COMMIT_TAG}-$[[ inputs.snapshot ]]
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_REF_NAME == "main"

stages:
  - build

.kas-build:
  stage: build
  image: ghcr.io/siemens/kas/kas-isar:4.8.2
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: "1"
    DEBIAN_SNAPSHOT: $[[ inputs.snapshot ]]
  script:
    - build_target="${TARGET}"
    - if [ "$DEBIAN_SNAPSHOT" != "" ];then build_target="$build_target:kas/opt/use-debian-snapshot.yml"; fi
    - echo "Building ${build_target}"
    - kas build ${build_target}
  tags:
    - privileged

build-pxe-boot-server-qemuamd64-to-qemuamd64:
  extends:
    - .kas-build
  variables:
    TARGET: "kas-pxe-boot.yml"
  artifacts:
    when: on_success
    name: "${CI_PROJECT_NAME}_qemuamd64_${BUILD_TAG}"
    expire_in: "30 days"
    paths:
      - build/tmp-pxe-boot-server-*/deploy/images/*/*.wic.xz
      - build/tmp-pxe-boot-server-*/deploy/images/*/*.manifest

build-pxe-boot-server-virtualbox-to-x86-pc:
  extends:
    - .kas-build
  variables:
    TARGET: "kas-pxe-boot-virtualbox-example.yml"
  artifacts:
    when: on_success
    name: "${CI_PROJECT_NAME}_virtualbox_${BUILD_TAG}"
    expire_in: "30 days"
    paths:
      - build/tmp-pxe-boot-server-*/deploy/images/*/*.ova.xz
      - build/tmp-pxe-boot-server-*/deploy/images/*/*.manifest

build-pxe-boot-server-vmware-to-x86-pc:
  extends:
    - .kas-build
  variables:
    TARGET: "kas-pxe-boot-vmware-example.yml"
  artifacts:
    when: on_success
    name: "${CI_PROJECT_NAME}_vmware_${BUILD_TAG}"
    expire_in: "30 days"
    paths:
      # Don't store binary artifacts for this build step, as they exceed the size limits
      #- build/tmp-pxe-boot-server-*/deploy/images/*/*.ova.xz
      - build/tmp-pxe-boot-server-*/deploy/images/*/*.manifest
