#
# Copyright (c) Siemens AG, 2025
#
# Authors:
#  Alexander Heinisch <alexander.heinisch@siemens.com>
#
# SPDX-License-Identifier: MIT
#

header:
  version: 14

build_system: isar

defaults:
  repos:
    patches:
      repo: meta-isar-pxeboot

repos:
  meta-isar-pxeboot:
  isar:
    url: https://github.com/ilbers/isar.git
    commit: d8a42c3ad4a68276012f68242b7edbb779de8f39
    layers:
      meta:
      meta-isar:

local_conf_header:
  ccache: |
    USE_CCACHE = "1"

  enable-pn-overrides: |
    OVERRIDES .= ":pn-${PN}"

  default-hostname: |
    HOSTNAME ??= "${MACHINE}"
